version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: productcatalog-postgres
    environment:
      POSTGRES_PASSWORD: productcatalog
      POSTGRES_USER: productcatalog
      POSTGRES_DB: productcatalog
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_productcatalog.sh:/docker-entrypoint-initdb.d/init_productcatalog.sh

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U productcatalog -d productcatalog" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - productcatalog-network

volumes:
  postgres_data:

networks:
  productcatalog-network:
    driver: bridge