version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: productcatalog-postgres
    environment:
      POSTGRES_PASSWORD: productcatalog
      POSTGRES_USER: productcatalog
      POSTGRES_DB: productcatalog
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U productcatalog -d productcatalog"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - productcatalog-network

  liquibase:
    image: liquibase/liquibase
    depends_on:
      - postgres
    volumes:
    - ./src/main/resources/db/changelog:/liquibase/changelog
    - ./src/main/resources/application.yml:/liquibase/application.yml
    working_dir: /resource
    command: --defaults-file=resource/application.yml update

volumes:
  postgres_data: