version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: productcatalog
      POSTGRES_USER: productcatalog
      POSTGRES_DB: productcatalog
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  liquibase:
    image: liquibase/liquibase
    depends_on:
      - postgres
    volumes:
    - ./main/resources/db/changelog:/liquibase/changelog
    - ./main/resources/liquibase.properties:/liquibase/liquibase.properties
    working_dir: /resource
    command: --defaults-file=resource/liquibase.properties update

volumes:
  postgres_data: